export PYTHONPATH="$HOME/.config/powerline"
export GOPATH="$HOME/Development/Go"
export PATH="$HOME/Development/dotfiles/bin:/usr/local/share/python:$PATH"

fpath+=(~/Development/dotfiles/zsh/prompt)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH="$PATH:/usr/local/share/npm/bin"
export PATH="$PATH:/usr/local/opt/ruby/bin"
export PATH="$PATH:/usr/local/lib/python2.7/site-packages"
export PATH="$PATH:/usr/local/heroku/bin"
export PATH="$PATH:$GOPATH/bin"

# Give detailed report for all commands taking more than 5 seconds
export REPORTTIME=5
export TIMEFMT='
> %J

  | Time:   [38;5;159m%*E[0m total time, %U user time, %S kernel time
  | Disk:   [38;5;159m%F[0m major page faults (pages loaded from disk)
  | System: [38;5;159m%P[0m CPU used, [38;5;159m%M[0m KB max memory used'

autoload -U colors && colors

alias less="less -j 4" # LESS: Find result 4 lines from top
alias tails="multitail"
alias json="python -m json.tool"
alias bower="bower --allow-root"
alias colors="pygmentize -O encoding=utf-8 -O style=monokai -g"
