export LC_ALL=en_US.utf-8

source ~/share/profile.d/20ezdev.sh

export PYTHONPATH="$HOME/.config/powerline"
export PATH="$HOME/Development/dotfiles/bin:$PATH"

fpath+=(~/Development/dotfiles/zsh/prompt ~/local/compdef)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH="$PATH:/usr/local/share/npm/bin"
export PATH="$PATH:/usr/local/opt/ruby/bin"
export PATH="$PATH:/usr/local/lib/python2.7/site-packages"
export PATH="$PATH:/usr/local/heroku/bin"
export PATH="$PATH:$HOME/bin"

export PATH="$PATH:/var/www/drupal/bin"
export PATH="$PATH:/var/www/magento/bin"

# Give detailed report for all commands taking more than 5 seconds
export REPORTTIME=5
export TIMEFMT='
> %J

  | Time:   [38;5;159m%*E[0m total time, %U user time, %S kernel time
  | Disk:   [38;5;159m%F[0m major page faults (pages loaded from disk)
  | System: [38;5;159m%P[0m CPU used, [38;5;159m%M[0m KB max memory used'

autoload -U colors && colors

alias less="less -j 4" # LESS: Find result 4 lines from top
alias tails="multitail"
alias bower="bower --allow-root"
alias colors="pygmentize -O encoding=utf-8 -O style=monokai -g"
alias ag="ag --path-to-agignore=$HOME/Development/dotfiles/agignore"
