# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH="$PATH:/usr/local/share/npm/bin"
export PATH="$PATH:/usr/local/lib/python2.7/site-packages:/usr/local/share/python"
export PATH="$PATH:/usr/local/heroku/bin"

# LESS: Find result 4 lines from top
alias less="less -j 4"
